import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<head>
				<meta charSet="utf-8"></meta>
				<meta httpEquiv="X-UA-Compatible" content="IE=9"></meta>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				></meta>
				<title>{process.env.CHATAPPNAME}</title>
				<link href="/static/css/bootstrap.min.css" rel="stylesheet"></link>
				<link href="/static/css/font-awesome.min.css" rel="stylesheet"></link>
			</head>
			<body className={inter.className}>
				<div className="container">{children}</div>
				<script src="/static/js/jquery-2.1.1.min.js"></script>
				<script src="/static/js/bootstrap.min.js"></script>
			</body>
		</html>
	);
}
